- name: install base packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
     - build-essential
     - curl
     - git
     - libssl-dev
     - vim

- name: download npm script
  command: curl -o /setup_6.x https://deb.nodesource.com/setup_6.x

- name: executing npm install script
  command: bash -c 'source /setup_6.x'

- name: install node
  apt: name=nodejs state=present update_cache=yes
